-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II 64-Bit Version 9.1 (Build Build 222 10/21/2009)
-- Created on Mon Sep 23 23:20:25 2019

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

--  Entity Declaration

ENTITY sdisp IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		A : IN integer range 9 downto 0;
		B : OUT STD_LOGIC_VECTOR(7 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END sdisp;


--  Architecture Body

ARCHITECTURE sdisp_architecture OF sdisp IS

	
BEGIN
 process(A)
  
  begin
    case A is  --Of Yin-level digital tube
      when 0 => B<="11000000";
      when 1 => B<="11111001";
      when 2 => B<="10100100";
      when 3 => B<="10110000";
      when 4 => B<="10011001";
      when 5 => B<="10010010";
      when 6 => B<="10000010";
      when 7 => B<="11111000";
      when 8 => B<="10000000";
      when 9 => B<="10010000";
    end case;
      
  end process;
END sdisp_architecture;
