-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2009 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.


-- Generated by Quartus II 64-Bit Version 9.1 (Build Build 222 10/21/2009)
-- Created on Fri Sep 20 17:44:16 2019

LIBRARY ieee;
USE ieee.std_logic_1164.all;


--  Entity Declaration

ENTITY disp2 IS
	-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	PORT
	(
		E : IN integer range 2 downto 0;
		O : OUT STD_LOGIC_VECTOR (2 downto 0)
	);
	-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!
	
END disp2;


--  Architecture Body

ARCHITECTURE disp2_architecture OF disp2 IS

	
BEGIN
process(E) 
     begin 
        case E is
          when 2 =>O<="100";
          when 1 =>O<="010";
          when 0 =>O<="001";
          end case;
     end process;

END disp2_architecture;
